Airlines.MVC/Controllers/AirlineController.cs
using Airlines.Domain.Models;
using Airlines.Domain.Services;
using Airlines.MVC.App_Start;
using Serilog;
using ServiceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airlines.MVC.Controllers
{
    public class AirlineController : Controller
    {
        private readonly IAirlineService _airlineService;

        public AirlineController()
        {
            _airlineService = (IAirlineService)DependencyResolver.Current.GetService(typeof(IAirlineService));
        }

        public ActionResult Index()
        {
            var res = Executer.ExecuteAndLog(GetAllAirlines, "Datos");
            if (res.success)
                Log.Debug("Han visitado la pagina de aerolineas");
                Log.Information("Va de locos");
            {
                return View(res.data);
            }
            return View();
        }

        private List<Airline> GetAllAirlines()
        {
            List<Airline> list = new List<Airline>();
            try
            {
                list = _airlineService.GetAll();
            }
            catch (Exception)
            {
                Log.Error("Error with airline services");
            }
            return list;
        }
    }
}

Airlines.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airlines.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Airlines.MVC/Controllers/InvoicesController.cs
using Airlines.Domain.Services;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airlines.MVC.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly IInvoicesService _airlineService = (IInvoicesService)DependencyResolver.Current.GetService(typeof(IInvoicesService));

        // GET: Invoices
        public ActionResult Index()
        {
            try
            {
                var data = _airlineService.GetAll();
                Log.Debug("Han visitado la pagina de invoices");
                return View(data);
            }
            catch (Exception)
            {
                Log.Information("Fallo en el servicio de aerolineas");
            }
            return View();
        }
    }
}

Airlines.MVC/Controllers/PassengerController.cs
using Airlines.Domain.Services;
using Serilog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airlines.MVC.Controllers
{
    public class PassengerController : Controller
    {
        private readonly IPassengersService _passengerService;

        public PassengerController()
        {
            _passengerService = (IPassengersService)DependencyResolver.Current.GetService(typeof(IPassengersService));
        }

        public ActionResult Index()
        {
            var data = _passengerService.GetAll();
            Log.Debug("Han visitado la pagina de passengers");
            return View(data);
        }
    }
}

Airlines.MVC/Views/Airline/index.cshtml
@model List<Airlines.Domain.Models.Airline>
@{
    ViewBag.Title = "index";
}
<table class="table">
    <tr>
        <td>id</td>
        <td>Name</td>
        <td>CreationYear</td>
        <td>AvgAnualInvoice</td>
    </tr>
    @foreach (var airline in Model)
    {
        <tr>
            <td>@airline.Id</td>
            <td>@airline.Name</td>
            <td>@airline.CreationYear</td>
            <td>@airline.AvgAnualInvoice</td>
        </tr>
    }
</table>

Airlines.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Airlines.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Airlines.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

Airlines.MVC/Views/Invoices/index.cshtml
@model List<Airlines.Domain.Models.Invoices>
@{
    ViewBag.Title = "index";
}
<table class="table">
    <tr>
        <td>PlaneRegistration</td>
        <td>Dni</td>
        <td>FlightDate</td>
        <td>Cost</td>
    </tr>
    @foreach (var p in Model)
    {
        <tr>
            <td>@p.PlaneRegistration</td>
            <td>@p.Dni</td>
            <td>@p.FlightDate</td>
            <td>@p.Cost</td>
        </tr>
    }
</table>

Airlines.MVC/Views/Passenger/index.cshtml
@model List<Airlines.Domain.Models.Passenger>
@{
    ViewBag.Title = "index";
}
<table class="table">
    <tr>
        <td>Dni</td>
        <td>Full Name</td>
        <td>Birth Date</td>
        <td>Retired</td>
    </tr>

    @foreach (var pas in Model)
    {
        <tr>
            <td>@pas.Dni</td>
            <td>@pas.FullName</td>
            <td>@pas.BirthDate</td>
            <td>@pas.Retired</td>
        </tr>
    }
</table>

Airlines.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zgz Airlines", "Index", "Airline", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Airlines", "Index", "Airline")</li>
                    <li>@Html.ActionLink("Passengers", "Index", "Passenger")</li>
                    <li>@Html.ActionLink("Invoices", "Index", "Invoices")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>